0428/workshop/crud/accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

0428/workshop/crud/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
]

0428/workshop/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

0428/workshop/crud/accounts/models.py
from django.db import models

0428/workshop/crud/articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

0428/workshop/crud/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article 
        exclude = ['created_at', 'updated_at', 'user',]

0428/workshop/crud/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

0428/workshop/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm


def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

0428/workshop/crud/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>LOGIN</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

0428/workshop/crud/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>SIGNUP</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

0428/workshop/crud/articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
  <h2>CREATE</h2>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock %}

0428/workshop/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>INDEX</h2>
  <a href="{% url 'articles:create' %}">NEW</a>
  {% for article in articles %}
    <ul>
      <li>{{ article.user }}의 {{ article.pk }}번글</li>
      <li>제목: {{ article.title }}</li>
      <li>내용: {{ article.content }}</li>
    </ul>
    <hr>
  {% endfor %}
{% endblock %}

0428/workshop/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>exercise</title>
</head>
<body>
  <h1>Articles</h1>
  {% if user.is_authenticated %}
    <h2>{{ user.username }}님 안녕하세요!</h2>
    <a href="{% url 'accounts:logout' %}">LOGOUT</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">LOGIN</a>
    <a href="{% url 'accounts:signup' %}">SIGNUP</a>
  {% endif %}
  <hr>
  {% block content %}
  {% endblock %}
</body>
</html>